### ISSUE TITLE
Script not pulling read_dates

### ISSUE THREAD

**Issue by dhmontgomery** [PaulKlinger/Enhance-GoodReads-Export#1]
When I run this script, it pulls genre information as intended. But the read_dates column is entirely blank for all of my more than 300 books in my library export. Can provide more information as necessary about what I'm experiencing.

**Comment by PaulKlinger** [comment]
Thanks for the heads up! Seems like goodreads changed the layout recently, the reading timeline is no longer displayed on the book page.

I've adapted the script, it should work again now.

**Comment by dhmontgomery** [comment]
Perfect! Now my only problem is my occasional user failure to input the "Date Started" field!
