### ISSUE TITLE
Really Stuck

### ISSUE THREAD

**Issue by Rellwood1221** [PaulKlinger/Enhance-GoodReads-Export#10]
Getting login page
Getting email login page
Logging in
Error logging in: Invalid URL '/errors/validateCaptcha': No scheme supplied. Perhaps you meant http:///errors/validateCaptcha?

Please?  I will pay if you fix this :)

**Comment by nomeutentepippo** [comment]
same problem here :(

**Comment by Dunnamore** [comment]
> Getting login page Getting email login page Logging in Error logging in: Invalid URL '/errors/validateCaptcha': No scheme supplied. Perhaps you meant http:///errors/validateCaptcha?
> 
> Please? I will pay if you fix this :)



> same problem here :(

Just keep pressing the "start processing" button, it might work eventually (works for me).

**Comment by Rellwood1221** [comment]
I have had it work for a couple of lines, but then it changes back.

**Comment by PaulKlinger** [comment]
This should be fixed in the latest version. 
I've changed the login process to use a browser-based method instead of trying to replicate it myself. So now it should open a browser window, you login there as if you're visiting goodreads normally, and then press continue / enter in the tool.
That should hopefully keep working / or at least be easy to fix if amazon change the login flow again.

**Comment by Rellwood1221** [comment]
Ok, I am testing it, so far I was able to log in and start the process.
Question: Did having my browser set to Firefox as my default have a
possible reason for the plugin not working in the past?  I'll let you know
how it goes.

Thank you SO FUCKING MUCH for this.
You have no idea how much this little .exe has improved my library!

Robin

**Comment by Rellwood1221** [comment]
So, It seems that it keeps getting the following message:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "enhance_goodreads_export\gui.py", line 42, in task
  File "enhance_goodreads_export\enhance_export.py", line 211, in
enhance_export
  File "backoff\_sync.py", line 110, in retry
  File "enhance_goodreads_export\enhance_export.py", line 142, in
update_book_data
  File "backoff\_sync.py", line 110, in retry
  File "enhance_goodreads_export\enhance_export.py", line 58, in
get_with_retry
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
https://www.goodreads.com/review/edit/20871425

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "enhance_export_gui.py", line 8, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in
_freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'


I figured out the problem. A lot of my books are no longer valid on
Goodreads. They still show up in my library, and they still have all the
read dates and I can still update them, but I cannot find them on Goodreads
outside my libary, so getting a genre for them is impossible. Is it
possible to add a feature to the plugin that either allows you to skip
books with errors and go back to chugging away, OR allow the user to select
the things that they want to tack on - ie just the read dates or Just the
genres, or just the number of reviews.
This might help in cutting down on problems when you can't get genres or
reviews from my booklist but you can get the readdates.

They are older books that have been rated but they can't be re-added to the
site. I found this out the hard way when I deleted a bunch of my "To Be
Read" shelf but when I ended up trying to put the books back on there was
no way to add them.

Let me go through my list and find books that might be a problem.

I'll get back to you.

**Comment by PaulKlinger** [comment]
The 403 issue should hopefully be fixed in the latest version, and I added an "ignore errors" option to keep going if a book fails to process

**Comment by Rellwood1221** [comment]
Yes. Finally, Fixed, no problems!
Got it to run through without any stops.
Thanks so much!

Robin
