### ISSUE TITLE
Executable flagged as Trojan:Win32/Zpevdo.A by Windows Defender

### ISSUE THREAD

**Issue by orenh1** [PaulKlinger/Enhance-GoodReads-Export#2]
According to Windows Defender, the prebuilt Windows executable contains the virus Trojan:Win32/Zpevdo.A!

**Comment by PaulKlinger** [comment]
It seems like this is a common false positive for python applications
packaged using pyinstaller. E.g. this project has the same issue:
https://github.com/spesmilo/electrum/issues/4986

I don't think there's much I can do to fix this unfortunately :(

**Comment by PaulKlinger** [comment]
I've sent the file to microsoft for review, hopefully the false positive will be corrected in a future windows defender update.

**Comment by orenh1** [comment]
Ok, good to know.

I ended up running the Python version instead (not before I read it over to make sure it wasn't doing anything suspicious...). Thanks for writing this!
