### ISSUE TITLE
Stalls on Login Page

### ISSUE THREAD

**Issue by Rellwood1221** [PaulKlinger/Enhance-GoodReads-Export#3]
I think Goodreads changed their login page because the .exe stalls at "getting login page"

Checking the network traffic when I select "start process" and there is a spike in activity then it stops.  Please, PLEASE fix this, Goodreads has no way of showing their multiple dates read and genres in their exports and I use CALIBRE to keep track of the many books I have read.  If I could donate to the cause I would.

Can't get it to go any further.  Last used April 2022 no problems

Using Windows 10 and the standalone .exe version

**Comment by PaulKlinger** [comment]
It looks like they are using a much more complicated amazon login page now. I finally got it to work, but there's still some work to package everything up. It's using captchas now, so I'll have to show that to the user.

I'll see if I can release a new version over the weekend.

**Comment by PaulKlinger** [comment]
@Rellwood1221 Should be fixed in the latest version: https://github.com/PaulKlinger/Enhance-GoodReads-Export/releases/latest

Please let me know if it works for you. You might have to solve a captcha during login, that's due to the new login process:
![Screenshot 2022-05-13 004032](https://user-images.githubusercontent.com/373570/168184480-616e8861-8230-4607-803f-a28abb62bd5c.png)

**Comment by Rellwood1221** [comment]
Thank you so much!  It runs now.  Please, PLEASE, keep this plugin up to date if possible.  Since there is no possible way to get all the read dates and genres any other way.  I understand that Goodreads is going to be phasing out their API access so I don't know what that means but if there is a way around that please find it.  I use Calibre exclusively for my extensive collection and this .exe has been such a godsend in keeping track of dates and getting elusive genres that Goodreads is not able to give.

Is there a way to donate?

**Comment by PaulKlinger** [comment]
Happy to help! It's great to see people find it useful 😊

I'll do my best to keep it running (let me know if it breaks again), but I can't promise it will always be possible. The API shutting down doesn't matter, as I'm just scraping the site itself, but they can always add more complications to the login process which I won't be able to work around. 

(For the current change the only reason I could fix it was that @mkb79 [had already done the work](https://github.com/mkb79/Audible) of figuring out how to make the amazon login process work.)

No need to give me any money, but feel free to send it to a [charity instead](https://www.givewell.org/maximum-impact-fund) 🙂
