### ISSUE TITLE
Goodreads Changed Their Columns

### ISSUE THREAD

**Issue by Rellwood1221** [PaulKlinger/Enhance-GoodReads-Export#5]
Book Id | Title | Author | Author l-f | Additional Authors | ISBN | ISBN13 | My Rating | Average Rating | Publisher | Binding | Number of Pages | Year Published | Original Publication Year | Date Read | Date Added | Bookshelves | Bookshelves with positions | Exclusive Shelf | My Review | Spoiler | Private Notes | Read Count | Owned Copies

**Comment by PaulKlinger** [comment]
Thanks for letting me know! Should work in [v0.7](https://github.com/PaulKlinger/Enhance-GoodReads-Export/releases/tag/v0.7)
