### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by josephholsten** [PaulKlinger/Enhance-GoodReads-Export#6]
I’m trying to run the script in an environment where python2 is hard to install.

Would you be interested in a PR to support Python3? I notice https://github.com/mkb79/Audible/blob/master/src/audible/metadata.py has moved that way.

I’m probably not good enough to support 2 & 3 in the same code unless we’re lucky.

**Comment by PaulKlinger** [comment]
I'm using python 3 already:
https://github.com/PaulKlinger/Enhance-GoodReads-Export/blob/d338b17297eaa1c0f5bd9746092cdb6e1414b26d/mypy.ini#L2

What issue do you have running it?

**Comment by josephholsten** [comment]
Turns out it was https://peps.python.org/pep-0604/ usage breaking in my python 3.9. Sorry for crying wolf! Also woah, this is the first time I’ve had 3.9 fail because the code was too _modern_, good job! 

If you were writing a businessy tool, I’d argue to stick with 3.9 support because RHEL/Rocky 9 ship with 3.9. But instead I’m going to see if with packaging into a docker container.

Thanks for the good work, I was recommended this tool by the fine folks at thestorygraph.com.
