### ISSUE TITLE
Not a problem but a request

### ISSUE THREAD

**Issue by Rellwood1221** [PaulKlinger/Enhance-GoodReads-Export#7]
Is there ANY way of creating a column for the numer of ratings?  Goodreads shows the average rating but if there are only 10 people rating the book it skews the average rating when it's rated at 5 stars vs. a 4.3 star book with 150,000 reviewers.  I know it's scrapable since the Calibre plugin Goodreads has a function to get that, but I don't want to have to go through each of my books and get that data when I can get it and keep it updated with your .exe file.

Also, do you accept donations?

**Comment by PaulKlinger** [comment]
Good idea! I'll take a look this evening, shouldn't be a big deal to add.

No worries about donations, happy that it's useful :)

**Comment by PaulKlinger** [comment]
I just realised that things have changed quite a lot with the new book page, so even the existing functionality is broken currently. I'll fix it on the weekend, or maybe before that if I have time.

**Comment by Rellwood1221** [comment]
Ok, so I just now saw you updated it.  I totally forgot about the request and when I tried to use my version it stopped working altogether.  I downloaded the newest version and it is PERFECT!  Thanks! Please don't forget about this plugin because it has become integral to my library.  I currently have 4400 books in GR with 1500 read and about 700 re-reads.

**Comment by PaulKlinger** [comment]
@Rellwood1221 Thanks! Sorry, I completely forgot to reply here

Let me know if it ever breaks again, I don't use it too often so I might not notice otherwise

**Comment by Rellwood1221** [comment]
Thanks!

**Comment by Rellwood1221** [comment]
Hi!  I hope you get this, but look at the issues, because it has broke complely.  Pleaaaasssss....my Calibre Library is lost without this function...:)
